### ISSUE TITLE
handling of \everypar has changed, breaking \charsd in some cases

### ISSUE THREAD

**Issue by dbenjaminmiller** [rrthomas/stage#1]
https://github.com/schlcht/microtype/issues/15

See this issue for an example (use with microtype)

**Comment by rrthomas** [comment]
I have attempted to make things work without `\everypar`. It seems OK for a script of mine that uses `\charsd` a lot; let me know if it seems OK, and I'll make a new release.

**Comment by dbenjaminmiller** [comment]
Yep, it seems OK.

**Comment by rrthomas** [comment]
Thanks for confirming! I've uploaded a new release to CTAN.
